---
- name: Install load balancer packages
  package:
    name: "{{ load_balancer_packages }}"
    state: present

- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy

- name: Enable Haproxy
  service:
    name: "{{ payload }}"
    state: started
    enabled: true

- name: Restart HAProxy
  command: /bin/true
  notify: restart_haproxy

- name: collect facts about system services
  service:
    name: "{{ payload }}"
    state: startus
  register: services_state

- name: Debug
  debug:
    var: services_state
