---

- name: install Tomcat
  package:
    name: "{{ payload }}"
    state: present
    
- name: Create the Tomcat content directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: Change the main page of Tomcat
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html
    mode: 0644

- name: Restart Tomcat, because if in debugging something fails it would not get started
  command: /bin/true
  notify: restart_tomcat

- name: enable Tomcat
  service:
    name: "{{ payload }}"
    enabled: yes
